import os

WORKING_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
INPUT_PATH = ""
OUTPUT_PATH = ""
MODEL_PATH = ""
CHECKPOINT_PATH = ""
USE_GUI = False
EPISODES = 0
VALIDATION_EPSIODE = 1
NUM_EVAL_EPISODES = 1
COLLECT_EPISODES_PER_ITERATION = 1
BUFFER_SIZE = 0
LEARNING_RATE = 0.0
ENTROPY_RATE = None
FC_LAYER_PARAMS = (100,)
