import os

WORKING_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
INPUT_PATH = ""
OUTPUT_PATH = ""
MODEL_PATH = ""
CHECKPOINT_PATH = ""
USE_GUI = False
EPISODES = 0
VALIDATION_EPISODE = 1
NUM_EVAL_EPISODES = 1
NUM_PARALLEL_ENV = 1
COLLECT_EPISODES_PER_ITERATION = 1
LEARNING_RATE = 0.0
IMPORTANCE_CLIPPING = 0.2
FC_LAYER_PARAMS = (100,)
NUM_TRAIN_EPOCHS = 10
ENTROPY = 0
